project:
  type: website
  preview: 
    port: 3333
    watch-inputs: true
    navigate: true

website:
  title: "Quarto Research Blog"
  favicon: favicon.svg
  navbar:
    right:
      - icon: github
        href: https://github.com/kazuyanagimoto/quarto-research-blog
format:
  html:
    theme:
      - cosmo
      - custom.scss
